### ISSUE TITLE
It is recommended to use file path verification instead of MD5 verification

### ISSUE THREAD

**Issue by lonsn2** [diommsantos/Gx64Sync#12]
It is recommended to use file path verification instead of MD5 verification.
Because processing a file with x64DBg may result in multiple patches, once the patched file is debugged again, GSync will fail and prompt: Hypersync: It is not possible to sync the address The XXX module is not loaded!

**Comment by diommsantos** [comment]
Gx64Sync used use filepath verification instead of MD5 but that would cause problems when the Ghidra and the x64Dbg session were not in the same machine (which happens a lot when debugging inside a virtual machine and having ghidra on the physical machine). See #7. This said if filepath verficiation is something you want you can take a look at the following commit [File path verification](https://github.com/diommsantos/Gx64Sync/commit/35729a7dfd6f1a525d3493b5053501bc903f393b), but I will provide no support for this version of Gx64Sync.
