### ISSUE TITLE
Issue with x64DBG plugin

### ISSUE THREAD

**Issue by Wagonx** [diommsantos/Gx64Sync#14]
When the plugin is installed to version () of x64dbg and launched in a debug session, the plugin produces the following error.

`[x64Sync] ConfigManager: An error occurred while getting the configurations
`

![image](https://github.com/user-attachments/assets/8d7a6e89-e5b1-4e32-bd24-b38ef079234d)

**Comment by diommsantos** [comment]
That seems to be an error with the config.sync file. The x64Dbg plugin is able to open it but is not able to parse it, are you sure the file contains valid json? The file should be located in your user folder.

**Comment by Wagonx** [comment]
Embarrisinly it was not, seems I had a sneaky invisible character. This has been correct, and it now seems to load the config file. However, I cannot get the debugging session to connect to Ghidra on my other machine. Do they need to be listening on the same port, or is it fine that I have them listening on separate ports?

**Comment by diommsantos** [comment]
Yes, the ports need to be same. If you don't want to mess with the ports you can just delete the following variable declarations from you config.sync files and they will default both to 9100:
"GSYNC_PORT" : ...
"X64SYNC_PORT" : ...
. Btw only the Ghidra Port listens for connections (the Ghidra plugin is the "server") the x64Sync port is the port the x64Dbg plugin should connect to (the x64Dbg plugin is the client). Hope that helps :)

**Comment by Wagonx** [comment]
Hmm, I've corrected this, but I'm still unable to establish a connection. Is there a way to get some more verbose logging on whats going on?

**Comment by diommsantos** [comment]
No, there isn't a way to get more verbose logging. Debugging the plugins is the only way right now to get more info on the errors. Some things to try:
1- If you are using Ghidra on a machine different from the machine you are using x64Dbg (virtual or physical machines) check that you have 2 config.sync each one in the user folder you are using of each machine.
2- The IPs in the config.sync files must match (the IP should be the one of your Ghidra machine x64SYNC_HOST is a bad name for the setting since this is the IP the plugin tries to connect to and doesn't host anything).
3- If everything above fails try to run both the Ghidra and x64Dbg plugin locally. If it functions correctly then the issue is something external to the plugins like firewall or router settings .

If you want to dig in the source code the files responsible for the connection are Client.hpp, Client.cpp in x64Sync and Listener.java and ClientHandler.java and a bit in SyncHandler.java in GSync. You can see the logic there for the connections there.

**Comment by Wagonx** [comment]
I misunderstood. I thought  x64SYNC_HOST was supposed to be the machine IP that the debugger was on. Everything works now, thank you so much. By the way, I am super excited to try your tool out. Thank yo again for all your help.

**Comment by diommsantos** [comment]
You're welcome :) ! If you would like to help the project the best way is to share it or contribute with pull requests of any type, new features, documentation, spelling typos, comment code (this part is especially lacking)....
