### ISSUE TITLE
Remote sync changes in Java code

### ISSUE THREAD

**Issue by mirek186** [diommsantos/Gx64Sync#7]
Thanks a lot for the remote code change in the x64dbg plugin.
While testing I've spotted a few minor issues to fix.
- The code is working, but there are no docs about the config file format being json but I've figured, e.g.
```
{
"X64SYNC_HOST":"192.168.56.125",
"X64SYNC_PORT":9100
}
```
- I'm running Ghidra on Kali Linux and the Java code also needs a config file where you can specify HOST, PORT or the workaround for now, I'm just listening on all interfaces with the following change in Listener.java
`        this.serverSocket = new ServerSocket(PORT, 0, InetAddress.getByAddress(new byte[] {0x00,0x00,0x00,0x00}));`
- Last change to get it to work is x64dbg plugin sends a full path of the module and when analyzing files in Ghidra, those are not in the same location, so the solution is to only compare filename, I know you might name clash but I think it's rare but I can't see another way around unless you want to recreate Windows folder structures on Linux. So there are two files LocationSync.java and HyperSync.java with the following changes:
```
for(; i < openpg.length; i++) {
                        String local_name = openpg[i].getExecutablePath().substring(openpg[i].getExecutablePath().lastIndexOf("/")+1);
                        String remote_name = ra.modPath.substring(ra.modPath.lastIndexOf("\\")+1);
                        if(local_name.equals(remote_name))
                        //if(openpg[i].getExecutablePath().substring(1).replace("/", "\\").equals(ra.modPath))
                                break;
                }
```

With the above it's all working brilliantly, big thank you for the plugin !!!
![ghidra1](https://github.com/user-attachments/assets/438f8b9e-808e-4c56-8961-258921eb9155)

**Comment by diommsantos** [comment]
- I wrote the documentation for `config.sync` at [Configuration](https://github.com/diommsantos/Gx64Sync?tab=readme-ov-file#configuration). If you find it confusing or difficult to follow please give me some feedback on how I can improve it or submit a pull request :)
- Ghidra has also a config file, if both Ghidra and x64Dbg are on the same file system is the same `config.sync` file. The variables relevant for Ghidra are: `GSYNC_HOST` and `GSYNC_PORT`. In your case you would write in your  **`config.sync` file in the Kali machine** (should be located in `$HOME/config.sync`):
```
{
"GSYNC_HOST": "0.0.0.0",
"GSYNC_PORT":9100
}
```
- Hadn't though about that problem when I allowed remote connections, I think that sending file hashes instead of file path would be a good solution that avoids naming collisions and allows the files to be on different file systems. I'll add this point to the TODO list

Thank you, if you like the plugin don't forget to share it ;)

**Comment by diommsantos** [comment]
I have implemented that instead of sending the module full path, it sends the module MD5 hash. This avoids name collisions and the paths being on different locations in the case of remote connections.

**Comment by mirek186** [comment]
Hi,

I can confirm that everything is working really well. I've tested both 32 and 64 version. The config file also works fine. The only thing I've noticed I had to use : not = for the JSON config file but in the docs you have =

**Comment by diommsantos** [comment]
Replaced the = for : in the docs
